USE DB_BI_Gpo01_24;
-- QUERY FOR FIRST CLEANSING OF OBTAINED DATA AFTER ANALYSIS 
SELECT [ENTIDAD],
[MUNICIPIO],
[AÑO],
[MES],
[HORA],
[MINUTO],
[DIA],
[DIASEMANA],
[ZONA],
[DETALLES_ZONA],
[TIPO_ACCIDENTE],
[NO_AUTOS],
[NO_CAMIONETAPASAJ],
[NO_MICROBUS],
[NO_CAMIONPASAJ],
[NO_OMNIBUS],
[NO_TRANVIA],
[NO_CAMIONETA],
[NO_CAMION],
[NO_TRACTOR],
[NO_FERROCARRIL],
[NO_MOTOCICLETA],
[NO_BICICLETA],
[NO_OTROVEHICULO],
[CAUSA],
[TIPO_SUPERFICIE],
[SEXO],
[RESP_EBRIEDAD],
[RESP_CINTURON],
[RESP_EDAD],
[NO_CONDMUERTO],
[NO_CONDHERIDO],
[NO_PASAMUERTO],
[NO_PASAHERIDO],
[NO_PEATMUERTO],
[NO_PEATHERIDO],
[NO_CICLMUERTO],
[NO_CICLHERIDO],
[NO_OTROMUERTO],
[NO_OTROHERIDO],
[NO_NEMUERTO],
[NO_NEHERIDO],
[CLASIFICACION],
CASE
WHEN [RESP_EDAD] >= 18 THEN 'Adulto'
WHEN [RESP_EDAD] = 0 THEN 'Desconocido'
ELSE 'Menor'
END AS [RESP_ADULTO],
[NO_CONDHERIDO] +
[NO_PASAHERIDO] +
[NO_PEATHERIDO] +
[NO_CICLHERIDO] +
[NO_NEHERIDO] AS NO_HERIDOS,
[NO_CONDMUERTO] +
[NO_PASAMUERTO] +
[NO_PEATMUERTO] +
[NO_CICLMUERTO] +
[NO_NEMUERTO] AS NO_DEFUNCIONES,
IIF ([SEXO] = 'Desconocido', 'Huyó','No huyó') AS FUGA,
CASE
WHEN [ENTIDAD] IN ('Baja California', 'Chihuahua',
'Sinaloa', 'Jalisco', 'Nayarit',
'Morelos', 'Queretaro', 'San Luis Potosi',
'Nuevo Leon', 'Tabasco', 'Tamaulipas',
'Veracruz de Ignacio de la Llave',
'Yucatan', 'Mexico', 'Ciudad de México') THEN
'Obligatorio'
ELSE 'No Obligatorio'
END AS [SEGURO_REQUERIDO],
CASE
WHEN [RESP_EDAD] = 0 THEN 'Desconocido'
WHEN [RESP_EDAD] BETWEEN 12 AND 17 THEN '[12,18)'
WHEN [RESP_EDAD] BETWEEN 18 AND 26 THEN '[18,27)'
WHEN [RESP_EDAD] BETWEEN 27 AND 35 THEN '[27,36)'
WHEN [RESP_EDAD] BETWEEN 36 AND 50 THEN '[36,50)'
WHEN [RESP_EDAD] BETWEEN 50 AND 99 THEN '[50,99]'
WHEN [RESP_EDAD] > 99 THEN '>99'
ELSE 'Desconocido'
END AS RANGO_EDAD,
CASE
WHEN [DIASEMANA] in ('Sábado', 'Domingo') THEN 'Inhábil'
WHEN [DIA] = 1 AND [MES] = 1 THEN 'Inhábil'
WHEN [DIA] = 1 AND [MES] = 5 THEN 'Inhábil'
WHEN [DIA] = 25 AND [MES] = 12 THEN 'Inhábil'
WHEN [DIA] = 6 AND [MES] = 2 AND AÑO = 2017 THEN 'Inhábil'
WHEN [DIA] = 20 AND [MES] = 3 AND AÑO = 2017 THEN 'Inhábil'
WHEN [DIA] = 16 AND [MES] = 9 AND AÑO = 2017 THEN 'Inhábil'
WHEN [DIA] = 20 AND [MES] = 11 AND AÑO = 2017 THEN 'Inhábil'
WHEN [DIA] = 5 AND [MES] = 2 AND AÑO = 2018 THEN 'Inhábil'
WHEN [DIA] = 19 AND [MES] = 3 AND AÑO = 2018 THEN 'Inhábil'
WHEN [DIA] = 16 AND [MES] = 9 AND AÑO = 2018 THEN 'Inhábil'
WHEN [DIA] = 19 AND [MES] = 11 AND AÑO = 2018 THEN 'Inhábil'
WHEN [DIA] = 4 AND [MES] = 2 AND AÑO = 2019 THEN 'Inhábil'
WHEN [DIA] = 18 AND [MES] = 3 AND AÑO = 2019 THEN 'Inhábil'
WHEN [DIA] = 16 AND [MES] = 9 AND AÑO = 2019 THEN 'Inhábil'
WHEN [DIA] = 18 AND [MES] = 11 AND AÑO = 2019 THEN 'Inhábil'
else 'Hábil'
END AS TIPO_DIA
INTO TT_Accidentes02
FROM [dbo].[TT_Accidentes01];
