/**
QUERY FOR THE RETRIEVING OF DATA FROM DB AND CONSTRUCTION OF FIRST TABLE FOR ANALYSIS
**/

USE DB_BI_Gpo01_24;
-- QUERY FOR THE FIRST CORRECTION OF DATA
SELECT [ENTIDAD],
[MUNICIPIO],
[ANIO] AS AÑO,
[MES],
[HORA],
[MINUTO],
[DIA],
CASE
WHEN [DIASEMANA] = 'Miercoles' THEN 'Miércoles'
WHEN [DIASEMANA] = 'Sabado' THEN 'Sábado'
ELSE [DIASEMANA]
END AS DIASEMANA,
IIF ([URBANA] = 'Sin accidente en esta zona', 'SUBURBANA','URBANA') AS ZONA,
CASE
WHEN [URBANA] = 'Sin accidente en esta zona' THEN [SUBURBANA]
WHEN [SUBURBANA] = 'Sin accidente en esta zona' THEN [URBANA]
ELSE 'Sin información'
END AS [DETALLES_ZONA],
[TIPACCID] AS TIPO_ACCIDENTE,
[AUTOMOVIL] AS NO_AUTOS,
[CAMPASAJ] AS NO_CAMIONETAPASAJ,
[MICROBUS] AS NO_MICROBUS,
[PASCAMION] AS NO_CAMIONPASAJ,
[OMNIBUS] AS NO_OMNIBUS,
[TRANVIA] AS NO_TRANVIA,
[CAMIONETA] AS NO_CAMIONETA,
[CAMION] AS NO_CAMION,
[TRACTOR] AS NO_TRACTOR,
[FERROCARRI] AS NO_FERROCARRIL,
[MOTOCICLET] AS NO_MOTOCICLETA,
[BICICLETA] AS NO_BICICLETA,
[OTROVEHIC] AS NO_OTROVEHICULO,
[CAUSAACCI] AS CAUSA,
[CAPAROD] AS TIPO_SUPERFICIE,
IIF([SEXO] = 'Se fugó', 'Desconocido', [SEXO]) AS [SEXO],
IIF([ALIENTO] = 'Se ignora', 'Desconocido', [ALIENTO]) AS RESP_EBRIEDAD,
[CINTURON] AS RESP_CINTURON,
[EDAD] AS RESP_EDAD,
[CONDMUERTO] AS NO_CONDMUERTO,
[CONDHERIDO] AS NO_CONDHERIDO,
[PASAMUERTO] AS NO_PASAMUERTO,
[PASAHERIDO] AS NO_PASAHERIDO,
[PEATMUERTO] AS NO_PEATMUERTO,
[PEATHERIDO] AS NO_PEATHERIDO,
[CICLMUERTO] AS NO_CICLMUERTO,
[CICLHERIDO] AS NO_CICLHERIDO,
[OTROMUERTO] AS NO_OTROMUERTO,
[OTROHERIDO] AS NO_OTROHERIDO,
[NEMUERTO] AS NO_NEMUERTO,
[NEHERIDO] AS NO_NEHERIDO,
[CLASACC] AS CLASIFICACION,
[ESTATUS]
INTO TT_Accidentes01
FROM [dbo].[ST_Accidentes];
